
before_script:
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  ##
  ## Optionally, if you will be using any Git commands, set the user name and
  ## email.
  ##
  #- git config --global user.email "darth@empire.com"
  #- git config --global user.name "Darth Vader"

#
# Defines stages which are to be executed
#
stages:
  - build

#
# Stage "build":
#
build-packages:
  stage: build
  tags:
  - Slackware64
  - x86_64
  script:
    - ./configure --prefix=/usr
    - make
    - make dist
    - cd slackware
    - ./svgc.x86_32.SlackBuild
    - ./svgc.x86_64.SlackBuild
    - cd ..

  #
  # This stage is only executed for new tags
  #
  #only:
  #  - tags

  #
  # The files which are to be made available in GitLab:
  #
  artifacts:
    paths:
      - svgc-*.tar.gz
      - svgc-*.txz
