
before_script:
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  ##
  ## Optionally, if you will be using any Git commands, set the user name and
  ## email.
  ##
  #- git config --global user.email "darth@empire.com"
  #- git config --global user.name "Darth Vader"

#
# Defines stages which are to be executed
#
stages:
  - build
  - source-distribution
  - packages

#
# Stage "build":
#
build-job:
  stage: build
  tags:
  - Slackware64
  - x86_64
  script:
    - ./configure --prefix=/usr
    - make
  #
  # This stage is only executed for new tags (requires more DevOps activities)
  #
  only:
    - tags

source-distribution:
  stage: source-distribution
  tags:
  - Slackware64
  - x86_64
  script:
    - ./configure --prefix=/usr
    - make
    - make dist
    - lftp --user $LFTP_USER --password $LFTP_PASSWORD ftp.radix.pro -e "mkdir -f -p pub/svgc ; chmod 2777 pub/svgc ; quit"
    - lftp --user $LFTP_USER --password $LFTP_PASSWORD ftp.radix.pro -e "mput -e -O pub/svgc/ svgc-*.tar.gz ; quit"
  #
  # The files which are to be made available in GitLab:
  #
  artifacts:
    name: "source-distribution"
    paths:
      - svgc-*.tar.gz
  #
  # This stage is only executed for new tags (requires more DevOps activities)
  #
  only:
    - tags

slackware-packages:
  stage: packages
  tags:
  - Slackware64
  - x86_64
  script:
    - ./configure --prefix=/usr
    - make
    - make dist
    - cd slackware
    - ./svgc.x86_32.SlackBuild
    - ./svgc.x86_64.SlackBuild
    - cd ..
    - lftp --user $LFTP_USER --password $LFTP_PASSWORD ftp.radix.pro -e "mkdir -f -p pub/svgc/slackware ; chmod 2777 pub/svgc/slackware ; quit"
    - lftp --user $LFTP_USER --password $LFTP_PASSWORD ftp.radix.pro -e "mput -e -O pub/svgc/slackware/ svgc-*.txz ; quit"
  #
  # The files which are to be made available in GitLab:
  #
  artifacts:
    name: "slackware-packages"
    paths:
      - svgc-*.txz
  #
  # This stage is only executed for new tags (requires more DevOps activities)
  #
  only:
    - tags
